id: P010445
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:50:16.453041
source_metadata:
  id: bdr:W2DB13644
  title: ཉི་ཐང་སྨན་མཁྱེན་གྱི་སྨན་ཡིག་དང་ནམ་མཁའ་སེངྒེའི་སྨན་རྩིས
  author: ''
  volumes:
    1713c597e4db44a6885575a5dc47390e:
      image_group_id: I1PD30933
      title: ''
      volume_number: 1
      total_pages: 432
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
