id: P010445
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB13644
  title: ཉི་ཐང་སྨན་མཁྱེན་གྱི་སྨན་ཡིག་དང་ནམ་མཁའ་སེངྒེའི་སྨན་རྩིས
  author: ''
  volumes:
    1713c597e4db44a6885575a5dc47390e:
      image_group_id: I1PD30933
      title: ''
      volume_number: 1
      total_pages: 432
      base_file: v001.txt
